package bookOrder
import com.scb.drools.entity.Order

//< $100
rule "book_Order_1"
    when
        $order:Order(originalPrice < 100)
    then
        $order.setRealPrice($order.getOriginalPrice());
        System.out.println("success rule 1");
end

//$100 - $200
rule "book_Order_2"
    when
        $order:Order(originalPrice >= 100 && originalPrice < 200)
    then
        $order.setRealPrice($order.getOriginalPrice() - 20);
        System.out.println("success rule 2");
end

//$200 - $300
rule "book_Order_3"
    when
        $order:Order(originalPrice >= 200 && originalPrice < 300)
    then
        $order.setRealPrice($order.getOriginalPrice() - 50);
        System.out.println("success rule 3");
end

// > $400
rule "book_Order_4"
    when
        $order:Order(originalPrice >= 300)
    then
        $order.setRealPrice($order.getOriginalPrice() - 100);
        System.out.println("success rule 4");
end